FROM python:3.12-slim-bookworm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install gcc meson zlib1g-dev -y && \
    pip install --upgrade pip

RUN pip install macs3

CMD ["macs3", "--help"]