# Use the Miniconda3 base image
FROM continuumio/miniconda3:24.5.0-0

COPY ./dockerfile .

# Update and install necessary system packages and tools
RUN apt-get update -y && apt-get install -y \
    build-essential \
    libnss-sss \
    vim \
    wget \
    unzip \
    zlib1g-dev \
	# Clean up apt cache
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
	
# Ensure /usr/local/bin is in the PATH
ENV PATH="/usr/local/bin:${PATH}"

# Add conda-forge and bioconda channels, and create the 'icount' environment
RUN conda config --add channels conda-forge && \
    conda config --add channels bioconda && \
    conda create -n icount icount -y

# Ensure the environment is activated in new shell sessions
RUN echo "conda activate icount" >> ~/.bashrc

# Activate the environment and run the default command
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "icount"]

CMD ["iCount", "-h"]
