# Use the Miniconda3 base image
FROM continuumio/miniconda3

# Update and install necessary system packages and tools
RUN apt-get update -y && apt-get install -y \
    build-essential \
    libnss-sss \
    curl \
    vim \
    less \
    wget \
    unzip \
    zlib1g-dev \
    pigz && \
    # Install bedtools
    wget https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
    mv bedtools.static /usr/local/bin/bedtools && \
    chmod a+x /usr/local/bin/bedtools && \
    # Clean up apt cache
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
	
# Ensure /usr/local/bin is in the PATH
ENV PATH="/usr/local/bin:${PATH}"

# Add conda-forge and bioconda channels, and create the 'paraclu' environment
RUN conda config --add channels conda-forge && \
    conda config --add channels bioconda && \
    conda create -n paraclu paraclu -y

# Ensure the environment is activated in new shell sessions
RUN echo "conda activate paraclu" >> ~/.bashrc

# Activate the environment and run the default command
ENTRYPOINT ["conda", "run", "-n", "paraclu"]

