FROM debian:stable-slim

COPY ./dockerfile /

# set the environment variables
ENV fastp_version 0.23.4

# run update and install necessary tools
RUN apt-get update -y && apt-get install -y \
    build-essential \
    libnss-sss \
    vim \
    less \
    wget \
    unzip \
    zlib1g-dev \
    libdeflate-dev \
    libisal-dev

# install fastqc
WORKDIR /usr/local/bin/
RUN wget https://github.com/OpenGene/fastp/archive/v${fastp_version}.zip && \
	unzip v${fastp_version}.zip && \ 
	cd /usr/local/bin/fastp-${fastp_version} && \
	make && \
	make install && \
	cd .. && \
	rm -rf v${fastp_version} v${fastp_version}.zip

# set default command
CMD ["fastp"]
