FROM r-base:4.4.1

# Update base and install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        wget \
        curl \
        perl \
        gcc \
        g++ \
        zip \
        unzip \
        gzip \
        make

# Install dependencies for R packages
RUN apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev

# Install samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.20/samtools-1.20.tar.bz2 && \
    tar -xvf samtools-1.20.tar.bz2 && \
    cd samtools-1.20 && \
    ./configure --prefix=/samtools && \
    make && \
    make install
ENV PATH="/samtools/bin:$PATH"

# Install DESeq2 and edgeR
RUN R -e "install.packages('BiocManager')" && \
    R -e "BiocManager::install('DESeq2')" && \
    R -e "BiocManager::install('edgeR')"

# Install HOMER
RUN wget http://homer.ucsd.edu/homer/configureHomer.pl && \
    perl configureHomer.pl -install
