FROM python:3.9.19-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get upgrade -y && \
    pip install --upgrade pip && \
    pip install \
        numpy \
        pandas \
        matplotlib \
        seaborn \
        openpyxl