FROM python:3.11.9-slim

COPY ./dockerfile /

RUN apt-get update && \
	apt-get install -y \
	build-essential \
	git \
	zlib1g-dev \
	wget \
	make \
	unzip \
	gcc && \
    apt-get clean && \
    pip install --upgrade pip
	
RUN wget https://github.com/CGATOxford/UMI-tools/archive/refs/tags/1.1.5.zip && \
	unzip 1.1.5.zip && \
	cd UMI-tools-1.1.5 && \
	python setup.py install --prefix=/usr/local

# Ensure /usr/local/bin is in the PATH
ENV PATH="/usr/local/bin:${PATH}"

# set perl locale settings
ENV LC_ALL=C

# Set default command	
CMD ["umi_tools"]
